config/routes.rb
Rails.application.routes.draw do
  root 'root_page#home'
  get  '/about', to: 'root_page#about'
  get  '/signup', to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get 'posts/new',   to: 'posts#new'
  get 'posts/:id',   to: 'posts#show'
  get 'users/edit',   to: 'users#edit'
  get '/liked_index', to: 'posts#liked_index'
  post   '/like/:post_id', to: 'likes#like',   as: 'like'
  delete '/like/:post_id', to: 'likes#unlike', as: 'unlike'
  post   '/gone/:post_id', to: 'gones#gone',   as: 'gone'
  delete '/gone/:post_id', to: 'gones#ungone', as: 'ungone'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :posts, only: [:index, :show, :create, :new, :destroy] do
    resources :comments, only: [:create]
  end
end

app/models/gone.rb
class Gone < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :user_id, presence: true
  validates :post_id, presence: true
end

app/controllers/gones_controller.rb
class GonesController < ApplicationController
    before_action :set_variables

  def gone
    gone = current_user.gones.new(post_id: @post.id)
    gone.save
    like = current_user.likes.find_by(post_id: @post.id)
    like.destroy
  end
  
  def ungone
    gone = current_user.gones.find_by(post_id: @post.id)
    gone.destroy
  end
  
  private

  def set_variables
    @post = Post.find(params[:post_id])
    @id_name = "#gone-link-#{@post.id}"
  end
end

app/helpers/gones_helper.rb
module GonesHelper
end

app/views/gones/_gone.html.erb
<% if !current_user?(post.user) %>
  <div class="like">
    <div id="gone-link-<%= post.id %>">
      <% if current_user.gones.find_by(post_id: post.id) %>
        <%= link_to ungone_path(post.id), method: :delete, remote: true do %>
          <span data-toggle="tooltip" title="「私のyumegulist」に追加済みだよ！もう一回押すとリストから削除されるよ！">
          <%= button_tag(class: "btn") do %>
          <%= content_tag :span, "", class: "glyphicon glyphicon-star", style: "font-size: 30px; color:yellow;" %>
          </span>
          <% end %>
        <% end %>
      <% else %>
        <%= link_to gone_path(post.id), method: :post, remote: true do %>
          <span data-toggle="tooltip" title="☆を押すと「私のyumegulist」に追加されるよ！">
          <%= button_tag(class: "btn") do %>
          <%= content_tag :span, "", class: "glyphicon glyphicon-star-empty", style: "font-size: 30px; color:yellow;" %>
          </span>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/gones/gone.js.erb
$("<%= @id_name %>").html('<%= escape_javascript(render("gones/gone", post: @post  )) %>');

app/views/gones/ungone.js.erb
$("<%= @id_name %>").html('<%= escape_javascript(render("gones/gone", post: @post  )) %>');