config/routes.rb
Rails.application.routes.draw do
  root 'root_page#home'
  get  '/about', to: 'root_page#about'
  get  '/signup', to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get 'posts/new',   to: 'posts#new'
  get 'posts/:id',   to: 'posts#show'
  get 'users/edit',   to: 'users#edit'
  get '/liked_index', to: 'posts#liked_index'
  post   '/like/:post_id', to: 'likes#like',   as: 'like'
  delete '/like/:post_id', to: 'likes#unlike', as: 'unlike'
  post   '/gone/:post_id', to: 'gones#gone',   as: 'gone'
  delete '/gone/:post_id', to: 'gones#ungone', as: 'ungone'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :posts, only: [:index, :show, :create, :new, :destroy] do
    resources :comments, only: [:create]
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :user_id, presence: true
  validates :post_id, presence: true
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_variables

  def like
    like = current_user.likes.new(post_id: @post.id)
    like.save
  end

  def unlike
    like = current_user.likes.find_by(post_id: @post.id)
    like.destroy
  end

  private

  def set_variables
    @post = Post.find(params[:post_id])
    @id_name = "#like-link-#{@post.id}"
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.erb
<% if !current_user?(post.user) %>
  <div class="like">
    <div id="like-link-<%= post.id %>">
      <% if current_user.likes.find_by(post_id: post.id) %>
        <%= link_to unlike_path(post.id), method: :delete, remote: true do %>
          <span data-toggle="tooltip" title="「行きたいところリスト」に追加済みだよ！もう一回押すとリストから削除されるよ！">
          <%= button_tag(class: "btn") do %>
           <%= content_tag :span, "", class: "glyphicon glyphicon-heart", style: "font-size: 30px; color:red;" %>
          </span> 
          <% end %>
        <% end %>
      <% else %>
        <%= link_to like_path(post.id), method: :post, remote: true do %>
          <span data-toggle="tooltip" title="♡を押すと「行きたいところリスト」に追加されるよ！">
          <%= button_tag(class: "btn") do %>
          <%= content_tag :span, "", class: "glyphicon glyphicon-heart-empty", style: "font-size: 30px; color:red;" %>
          </span>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/likes/like.js.erb
$("<%= @id_name %>").html('<%= escape_javascript(render("likes/like", post: @post  )) %>');

app/views/likes/unlike.erb
$("<%= @id_name %>").html('<%= escape_javascript(render("likes/like", post: @post  )) %>');

app/views/likes/unlike.js.erb
$("<%= @id_name %>").html('<%= escape_javascript(render("likes/like", post: @post  )) %>');