config/routes.rb
Rails.application.routes.draw do
  root 'root_page#home'
  get  '/about', to: 'root_page#about'
  get  '/signup', to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get 'posts/new',   to: 'posts#new'
  get 'posts/:id',   to: 'posts#show'
  get 'users/edit',   to: 'users#edit'
  get '/liked_index', to: 'posts#liked_index'
  post   '/like/:post_id', to: 'likes#like',   as: 'like'
  delete '/like/:post_id', to: 'likes#unlike', as: 'unlike'
  post   '/gone/:post_id', to: 'gones#gone',   as: 'gone'
  delete '/gone/:post_id', to: 'gones#ungone', as: 'ungone'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :posts, only: [:index, :show, :create, :new, :destroy] do
    resources :comments, only: [:create]
  end
end

app/controllers/root_page_controller.rb
class RootPageController < ApplicationController
  def home
  end
  
  def about
  end
end

app/helpers/root_page_helper.rb
module RootPageHelper
end

app/views/root_page/about.html.erb
<% provide(:title, "About") %>
  <h2>#yumegulistとは</h2>
  <p>東京都内に数ある銭湯や温泉施設の情報共有サイトです。</p>
  <div class="about">
    <p>①自分のお気に入りを投稿してみよう<br>位置情報も追加してみよう<p>
    <div class="new_post"></div>
  </div>
  <div class="about">
    <p>②みんなの投稿からお気に入りを探そう<br>気に入ったら「♡」を押してね</p>
    <div class="about_like"></div>
  </div>
  <div class="about">
    <p>③行きたいところリストに追加されるよ<br>地図をたよりに行ってみよう</p>
    <div class="about_liked_post"></div>
  </div>
  <div class="center">
      <%= link_to "新規会員登録して始める", signup_path, class: "btn btn-info" %>
  </div>

app/views/root_page/home.html.erb
<div class="top">
  <div class="masthead">
    <div class="container">
      <div class="center">
        <h1>#yumegulist</h1>
      </div>
      <div class="center">
        <%= link_to "#yumegulistとは", about_path, class: "btn btn-info" %>
        <%= link_to "新規会員登録", signup_path, class: "btn btn-info" %>
      </div>
      <div class="right">
        <P>東京に数ある銭湯や温泉、たくさん巡ってみよう。</P>
        <P>お気に入りが見つかったら、メモして共有しよう。</P>
        <P>みんなのお気に入りの場所をみて、また巡ろう。</P>
      </div>
    </div>
  </div>
</div>